<?php

//Terms and Condition array
	
	$prvcy1 = "<a href='#'>http://www.mySPEEDEM.com/privacy/index.html</a>";
	
	$TnCpntz_en = array(
					"<b>mySPEEDEM SMS END-USER LICENSE AGREEMENT</b>"=>"This is a legally binding agreement between you (either an individual or a single entity), referred to herein as “YOU”, and mySPEEDEM Inc, referred to herein as “mySPEEDEM”. This software entitled mySPEEDEM SMS and all documents and materials included in it are referred to herein as the “SOFTWARE” or the “DOCUMENTS”. Installing, opening or using all or any portion of this software indicates your acceptance of all the terms and conditions of this End-User License Agreement referred to herein as “EULA” and that this agreement is equivalent to a written agreement signed by you. By selecting the box “I AGREE” or performing a similar electronic function, you are providing your acceptance of the terms of this agreement. This agreement is enforceable against you and any legal entity that obtained the software and on whose behalf it is used. If you do not agree to the terms of this agreement, please do not use this software.
					<br>
					IT IS ILLEGAL AND STRICTLY PROHIBITED TO DISTRIBUTE, PUBLISH, OFFER FOR SALE, LICENSE OR SUBLICENSE, GIVE OR DISCLOSE TO ANY OTHER PARTY, THIS SOFTWARE OR THE DOCUMENTS IN HARD COPY, DIGITAL FORM OR ANY OTHER MEDIUM WHETHER EXISTING OR NOT YET EXISTING, EXCEPT AS SPECIFICALLY PERMITTED BELOW.
					<br>
					The use of this software is governed by the terms and conditions set forth herein. Please read them carefully. This EULA is applicable to all of the Documents included in the Software and to the Software in its whole part. You are deemed to have read, understood and accepted the terms of this EULA when you install or use the Software.",
					
					"LIMITED LICENSE"=>"You are granted a limited, non-exclusive license to install the Software on one individual computer for your own use provided that such computer does not render the Software accessible to other users through local or Internet networks or other methods. Only the individual that installed the Software, as indicated by the user information provided when installing the Software, will have the license to use the Documents. Use by any other person, company, affiliate, corporation, Limited Liability Company, trust, or other separate legal entity will require a separate license. This includes companies that may be affiliated to you by ownership or otherwise. The license granted herein shall remain in effect perpetually, but shall terminate upon your use of the Software beyond the scope licensed herein or upon your violation of any term or condition hereof. All protections with which mySPEEDEM is provided under this EULA shall survive the termination of your license to use the Software",
					
					"PROPRIETARY RIGHTS"=>"mySPEEDEM and its suppliers retain all title, ownership, and intellectual property rights in the Software, including but not limited to all supporting documentation, files, marketing material, images, multimedia and applets. The Software is protected by copyright and other intellectual property laws and by international treaties. The Software may include security measures designed to control access and prevent unauthorized copying and use. You agree not to interfere with any such security components. mySPEEDEM permits you to download, install, use, or otherwise benefit from the functionality or intellectual property of the Software only in accordance with the terms of this EULA. Use of third party material included in the Software may be subject to the terms and conditions typically found in the party's own license agreement",
					
					"CONFIDENTIALITY"=>"Each party agrees that it shall not disclose to any third party any information concerning the customers, trade secrets, methods, processes or procedures or any other confidential, financial or business information of the other party which it learns during the course of its performance of this EULA, without the prior written consent of such other party. This obligation shall survive the cancellation or other termination of this EULA. The Software contains trade secrets and proprietary know-how that belong to mySPEEDEM and it is being made available to you in strict confidence. ANY USE OR DISCLOSURE OF THE SOFTWARE, OR OF ITS ALGORITHMS, PROTOCOLS OR INTERFACES, OTHER THAN IN STRICT ACCORDANCE WITH THIS EULA, MAY BE ACTIONABLE AS A VIOLATION OF mySPEEDEM’S TRADE SECRET RIGHTS",
					
					"NON-TRANSFER OF RIGHTS"=>"You may not rent, lease, sell, sublicense, assign or transfer your rights in the software, or authorize any portion of the software to be copied onto another individual or legal entity's computer",
					
					"ALLOWED USAGE"=>"Upon fulfilling your obligations towards properly installing and registering the Software or obtaining a valid Software license key, you are permitted to do only the following:<br>
(a) Use the Documents in transactions and agreements in which you are one of the parties. You may have your attorney review, comment and modify the Documents to fit your particular needs. You are encouraged to obtain competent legal counsel to advise you on the use of the Documents and/or the contractual relationship you are establishing.
<br>
(b) Modify the Documents to fit your own needs and the contractual relationship you are entering.
<br>
(c) If you are an attorney, you may modify the Documents and use them only for preparing documents for your immediate clients with whom you have an attorney-client relationship. The attorney license is only for one individual attorney use. As such, only you can use the Documents. Other attorneys or associates within your firm cannot use the Documents. They must acquire a license for themselves.
<br>
(d) If you only have a license to use the free version of the Software, in order to transmit a digital version of any of the Documents, the receiving parties must also have a license to use the Software. If the other parties do not possess a license, you are encouraged to send them a link to download the Software and thereby acquire a license. These parties, and your attorney, may modify and make suggested changes to the Documents as part of the normal negotiation process or as part of your representation in a bona fide attorney-client relationship.
<br>
(e) Disclose any final executed Documents reflecting a consummated transaction or executed agreement to the SEC (or any other security regulation agency) where necessary as part of a required securities law filing and to other governmental agencies as part of a required filing.
<br>
(f) Display or post online as a part of your website or online property for your own use, only Documents that are meant for public display or use on a website, such as Online Licenses, Privacy Statements, Affiliate Program Agreements, Linking Agreements and the like.
<br>
(g) Include in the packaging and shipment of your product or in your product documentation, Documents that are meant to be distributed along with computer software or other product deliverables.(h) You may make one copy of the original media on which you obtained the Software solely for backup or archival purposes. You may not otherwise make copies of the Software. You agree that any copies of the Software which you make pursuant to this EULA shall bear all copyright, trademark and other proprietary notices included therein by mySPEEDEM and, except as expressly authorized herein, you shall not distribute the same to any third party without mySPEEDEM's prior written consent",
					
					"DISTRIBUTION"=>"You may not unpack or remove Documents and distribute them in any way except as prescribed by the Allowed Usage defined in section 5. Only distribution of the full and complete unaltered software application is allowed provided that mySPEEDEM has given you prior written authorization (through your participation in any of mySPEEDEM’s partner programs) and that all trademarks, ownership and copyright notices remain in the Software",
					
					"RESTRICTIONS"=>"You may not: 
<li>(i) modify or create any derivative works of the Software or documentation, including customization, any modifications or enhancements, translation or localization without mySPEEDEM's express written consent; 
<li>(ii) reverse engineer, decompile, disassemble, make or otherwise attempt to derive the source code of the Software, or the underlying ideas or algorithms of the Software; 
<li>(iii) attempt to gain unauthorized access to Documents, mySPEEDEM servers or any other service, account, computer system or network associated with the Software or with mySPEEDEM, it's affiliates, agents, partners and customers; 
<li>(iv) remove or alter any trademark, logo, copyright or other proprietary notices or symbols in the Software; 
<li>(v) block, disable, or otherwise affect any advertising, banner window, tab, link to websites and services, or other features that are part of the Software;
<li>(vi) incorporate, integrate or otherwise include the Software or any portion thereof into any software, program or product;
<li>(vii) provide false information when registering the Software;
<li>(viii) digitally transmit or make available the Software or its content through local networks, intranets, extranets, FTP, online discussion boards, forums, list-serve, peer-to-peer networks or technologies, newsgroups, bulletin boards, or any other mode of shared communication system, or place the Software onto a server so that it is accessible via a pubic network such as the Internet;
<li>(ix) use the Software in any way that violates this EULA or any law; or
<li>(x) authorize or assist any third party to do any of the things described in this section",
					
					"PUBLICITY"=>" You shall not refer to the existence of this EULA in any press release, website, advertising or any publicly distributed or accessible material, without the prior written consent of mySPEEDEM",
					
					"ADDITIONAL FEATURES & CONTENT"=>"Certain portions of the Software may be locked or unavailable in the free version. In order to upgrade the Software or use additional content and features you must (i) install the free version, (ii) provide valid registration information and (iii) pay a fee to obtain a valid Software license key. All Software license key holders are subject to the terms and conditions of this EULA",
					
					"SOFTWARE LICENSE KEY"=>"Certain features or content of the Software may require the purchase of a Software license key. You agree not to attempt to, and not to, control, disable, modify or remove any component of the Software license key protection system. You also agree not to access, attempt to access, copy, share or distribute the license key for any purpose",
					
					"SOFTWARE UPDATES"=>"The Software is configured to automatically check for updates. By using the Software, you consent to receiving software updates, modifications, and/or patches that address issues such as security, interoperability, and performance. Your use of the updates shall be governed by this EULA unless you are asked to agree to a new EULA at the time of download or installation",
					
					"PRIVACY"=>"(a) SOFTWARE IMPROVEMENT PROGRAM. <br> By participating in the mySPEEDEM Software Improvement Program, you allow mySPEEDEM to collect anonymous information relating to your use of the Software, such as the frequency of your use of the Software and of certain features, and information on errors occurring during your use of the Software. This anonymous usage data will be used to diagnose performance issues and improve the reliability of the Software and its features. This data will not be tied to any information that would personally identify you.
<br>
(b) PERSONAL INFORMATION. <br> During the installation process, or at some time thereafter, you may be asked to provide certain information that will be used to personalize certain Documents, send you mySPEEDEM information via email or mail, and customize some information presented to you through the Software. For example, you may be asked for your state/province/country, which could be used by the Software to provide you with locally relevant Documents and/or related products. All personal and billing information is transmitted using the secure SSL protocol. Both personal and non-personal information collected by the Software is safeguarded according to the highest privacy and data protection standards adopted worldwide, and will not be shared or given without your consent as described in our Privacy Policy (available at $prvcy1)",
					
					"LIMITATION OF LIABILITY"=>"EXCEPT AS REQUIRED BY LAW, mySPEEDEM AND ITS EMPLOYEES, DIRECTORS, LICENSORS, CONTRIBUTORS AND AGENTS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF OR IN ANY WAY RELATING TO THIS EULA OR THE USE OF OR INABILITY TO USE THE SOFTWARE, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, LOST PROFITS, LOSS OF DATA, AND COMPUTER FAILURE OR MALFUNCTION, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF THE THEORY (CONTRACT, TORT OR OTHERWISE) UPON WHICH SUCH CLAIM IS BASED. mySPEEDEM'S LIABILITY UNDER THIS EULA IS LIMITED TO REPLACEMENT OF A CD-ROM CONTAINING THE SOFTWARE AND WILL NOT EXCEED FIVE DOLLARS (US$5.00)",
					
					"DISCLAIMER OF WARRANTY"=>"YOU ACCEPT THE SOFTWARE “AS IS” AND WITH ALL FAULTS (IF ANY). mySPEEDEM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. mySPEEDEM MAKES NO WARRANTY OR REPRESENTATIONS WHATSOEVER REGARDING THE CONTENT OF THE DOCUMENTS AND YOUR USE OF THE DOCUMENTS, OR THE SUITABILITY OF THE DOCUMENTS TO MEET YOUR SPECIFIC NEEDS. THE DOCUMENTS ARE DETAILED, BUT GENERIC IN FORM. THERE MAY BE LAWS APPLICABLE IN YOUR STATE/PROVINCE/COUNTRY THAT NEED TO BE ADDRESSED IN ANY FINAL DOCUMENT. YOU ARE STRONGLY URGED TO OBTAIN COMPETENT LEGAL COUNSEL TO REVIEW THE DOCUMENTS YOU CREATE USING THE SOFTWARE AND TO ADVISE YOU ON ANY TRANSACTION IN WHICH YOU INTEND TO ENGAGE<br>
mySPEEDEM makes no warranties with respect to the Documents as described above and as such, there should be no reason for you to bring any grievance against mySPEEDEM. However, if you do bring any action, claim, suit, threat or demand against mySPEEDEM, and you do not substantially prevail, you shall pay mySPEEDEM’s entire attorney fees and costs attached to such action. In the same token, if mySPEEDEM is forced to take legal action to enforce this EULA or any of its rights described herein or under any state or federal law, you will pay mySPEEDEM’s attorney fees and costs",
					
					"VIOLATIONS OF THIS EULA"=>" mySPEEDEM reserves all rights not specifically granted to you above. mySPEEDEM will have the right to proceed against you in the event that you infringe against mySPEEDEM’s rights. Any use not within the precise scope of the license set forth herein will be considered an infringement. You acknowledge and agree that mySPEEDEM’s damages in the event of your violation of this EULA will be substantial and that mySPEEDEM will suffer irreparable harm in such event. As such, mySPEEDEM shall have the right to obtain equitable remedies, including but not limited to recovery of damages, obtaining injunctions, recovering statutory damages, recovering attorney fees, and any other available legal remedy",
					
					"TERMINATION"=>" mySPEEDEM shall have the sole and exclusive right to immediately terminate this EULA and suspend your license to use the Software should you fail to perform any obligation required under this EULA, engage in activity that mySPEEDEM deems harmful to its well-being or if you become bankrupt or insolvent. This EULA takes effect upon your installation of the Software and remains effective until terminated. Upon termination of this EULA by mySPEEDEM, you shall return to mySPEEDEM the original and all copies of the Software and Documents including partial copies and modifications",
					
					"WAIVER & SEVERABILITY"=>" mySPEEDEM's waiver of any breach of this EULA shall not constitute an amendment to this EULA or mySPEEDEM's waiver of subsequent breaches. If any part of this EULA is found void and unenforceable, it will not affect the validity of the balance of this EULA, which will remain valid and enforceable according to its terms",
					
					"RESTRICTED RIGHTS LEGEND FOR GOVERNMENTAL USE"=>"mySPEEDEM in its whole, like any Software, Documents, or other information that is downloaded through accessing mySPEEDEM’s website, partner websites and download sites for or on behalf of the United States of America, its agencies and/or instrumentalities (“U.S. Government”), is provided with Restricted Rights. Use, duplication, or disclosure by the U.S. Government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the Commercial Computer Software--Restricted Rights at 48 CFR 52.227-19, as applicable",
					
					"ELECTRONIC NOTICES"=>"You consent that mySPEEDEM may provide you with information and notices regarding the Software and mySPEEDEM via the email address you designate when installing the Software or thereafter. mySPEEDEM may provide notices to you via (i) email if you have provided mySPEEDEM with a valid email address, or (ii) by posting the notice on the mySPEEDEM website or the Software download site which mySPEEDEM owns and operates. You may withdraw your consent for electronic notices",
					
					"AMENDMENTS"=>"mySPEEDEM reserves the right to unilaterally amend all offers, pricing terms or other matters pertaining to the Software, mySPEEDEM’s website or this EULA. No course of dealing or trade usage shall be deemed to amend the terms of this EULA",
					
					"GOVERNING LAW"=>"This EULA shall be governed by and construed under the laws of the State of New York. You consent and agree that all legal proceedings relating to the subject matter of this EULA shall be maintained in courts sitting within the State of New York, and that jurisdiction and venue for such proceedings shall lie exclusively with such courts",
					
					"COMPLETE AGREEMENT"=>"This is the entire EULA between mySPEEDEM and you relating to the Software and it supersedes any prior representations, discussions, undertakings, warranties, communications or advertising relating to the Software",
					
					"For inquiries please contact:"=>"mySPEEDEM, <p>SPEEDEM CO. LTD.,<br>Tafo Pankrono - Atimatim, Monic Junction<br>Ashanti Region Ghana, West Africa<br>Tel: +233 265 997 977<br>E-mail: support@myspeedem.com<p>Copyright &copy; 2012. All rights reserved.<br>mySPEEDEM INC – Last revised: January 26, 2011",
										
					);
					
?>


